[package]
name = "socks5-srv"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
socks5-proxy = "0.1"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
